config/routes.rb
EummcrOrdering::Application.routes.draw do

  
  get 'settings', :to => 'settings#index', :as => :settings
  
  resources :orders
  
  root :to => 'orders#new'
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :ordered_products, :dependent => :destroy 
  
  accepts_nested_attributes_for :ordered_products, :allow_destroy => true, :reject_if => lambda { |a| a[:gene].blank? }
  
  validates_presence_of :recipient_institute_name
  validates_presence_of :recipient_institute_street
  validates_presence_of :recipient_institute_city
  validates_presence_of :recipient_institute_zip
  validates_presence_of :recipient_institute_country
  
  validates_presence_of :recipient_principal_scientist_person
  validates_presence_of :recipient_principal_scientist_institute
  validates_presence_of :recipient_principal_scientist_phone
  validates_presence_of :recipient_principal_scientist_email
  
  validates_presence_of :recipient_authorized_official_person
  validates_presence_of :recipient_authorized_official_phone
  validates_presence_of :recipient_authorized_official_fax
  
  validates_presence_of :subtotal_price
  validates_presence_of :shipping_price
  validates_presence_of :vat_price
  validates_presence_of :total_price
  
  validates :recipient_principal_scientist_email, :email => true
  validates :recipient_authorized_official_email, :email => true
end

app/models/ordered_product.rb
class OrderedProduct < ActiveRecord::Base
  belongs_to :order
  belongs_to :ordered_product_type
  
  attr_accessor :nested
  
  validates_presence_of :order_id, :on => :save, :unless => :nested
  validates_presence_of :ordered_product_type_id
  validates_presence_of :gene
  validates_presence_of :price
  
  validate :validate_solr_response
  
  before_save { |product| product.gene = find_in_solr['marker_symbol'] }
  
  def mgi_accession_id
    find_in_solr['mgi_accession_id']
  end
  
  private
  
  def validate_solr_response
    unless gene.nil?
      if find_in_solr.nil?
        errors.add( :gene, "unable to lookup details for this gene '#{gene}' from the IKMC - please try again in 10 minutes, or contact mouseportal@sanger.ac.uk" )
      end
    end
  end
  
  def find_in_solr
    solr_response = SOLR.get 'select', :params => { :q => "#{gene}" }
    docs          = []
    
    solr_response['response']['docs'].each do |doc|
      docs.push(doc) if doc['marker_symbol'].downcase == gene.downcase
    end
    
    docs.first
  end
end

app/models/ordered_product_type.rb
class OrderedProductType < ActiveRecord::Base
  has_many :ordered_products
  
  validates_uniqueness_of :product_type
  
  validates_presence_of :price
  validates_presence_of :shipping
  
  def clone_count
    match = product_type.match(/ES Cell Clones \((\d) Clone/)
    count = match[1].to_i if match
    return count || 0
  end
end

app/models/settings.rb
class Settings < ActiveRecord::Base
  validates_uniqueness_of :key, :scope => [:value]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :get_vat
  
  # GET /orders
  # GET /orders.xml
  def index
    @orders = Order.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.xml
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.xml
  def new
    @order = Order.new
    8.times { @order.ordered_products.build }
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.xml
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to(@order, :notice => 'Order was successfully created.') }
        format.xml  { render :xml => @order, :status => :created, :location => @order }
      else
        if @order.ordered_products.empty?
          8.times { @order.ordered_products.build }
        else
          no_times = 8 - @order.ordered_products.size
          no_times.times { @order.ordered_products.build }
        end
        format.html { render :action => "new" }
        format.xml  { render :xml => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.xml
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to(@order, :notice => 'Order was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.xml
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to(orders_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def get_vat
    @vat = Settings.where(:key => 'vat').first.value.to_f
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
    @settings = { 'product_type' => {} }
    
    Settings.all.each do |setting|
      if setting.value =~ /^\{/
        @settings[setting.key] = JSON.parse(setting.value)
      else
        @settings[setting.key] = setting.value
      end
    end
    
    OrderedProductType.all.each do |product_type|
      @settings['product_type'][product_type.id] = {
        :product_type => product_type.product_type,
        :price        => product_type.price,
        :shipping     => product_type.shipping,
        :clone_count  => product_type.clone_count
      }
    end
    
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json   { render :json => @settings.to_json }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EummcrOrdering</title>
  <%= stylesheet_link_tag :all %>
  <%= formtastic_stylesheet_link_tag %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/_form.html.erb
<%= semantic_form_for @order do |f| %>
  <%
    ordered_product_errors = []
    @order.errors.each do |attribute,errors_array|
      if attribute.to_s =~ /ordered_products/
        ordered_product_errors.push(errors_array) unless attribute.to_s == 'ordered_products.order_id'
      elsif attribute.to_s =~ /_price/ && errors_array.include?("can't be blank")
        ordered_product_errors.push('You have not ordered any products')
      end
    end
  %>
  <% if @order.errors.any? %>
    <div class="errorExplanation">  
      <h2>Errors were found when trying to process your order</h2>
      <p>Please review the information in the form below and correct any errors.</p>
    </div>
  <% end %>
  
  <%= f.inputs "Recipient's Institution", :id => "recipients_intitution" do %>
    <%= f.input :recipient_institute_name, :label => "Institution's Full Name" %>
    <%= f.input :recipient_institute_additional_address_line, :label => 'Additional Address Line' %>
    <%= f.input :recipient_institute_street, :label => 'Street' %>
    <%= f.input :recipient_institute_state, :label => 'State' %>
    <%= f.input :recipient_institute_city, :label => 'City' %>
    <%= f.input :recipient_institute_zip, :label => 'Zip-Code' %>
    <%= f.input :recipient_institute_country, :label => 'Country' %>
  <% end %>
  
  <%= f.inputs "Shipping Address", :id => "shipping_address" do %>
    <%= f.input :shipping_address_institute, :label => "Institution's Full Name" %>
    <%= f.input :shipping_address_person, :label => 'Person/Institute to Send Material to' %>
    <%= f.input :shipping_address_additional_address_line, :label => 'Additional Address Line' %>
    <%= f.input :shipping_address_street, :label => 'Street' %>
    <%= f.input :shipping_address_state, :label => 'State' %>
    <%= f.input :shipping_address_city, :label => 'City' %>
    <%= f.input :shipping_address_zip, :label => 'Zip-Code' %>
  <% end %>
  
  <%= f.inputs "Recipient Principal Scientist", :id => "recipient_principal_scientist" do %>
    <%= f.input :recipient_principal_scientist_person, :label => 'Full Name' %>
    <%= f.input :recipient_principal_scientist_institute, :label => 'Institute' %>
    <%= f.input :recipient_principal_scientist_additional_address_line, :label => 'Additional Address Line' %>
    <%= f.input :recipient_principal_scientist_street, :label => 'Street' %>
    <%= f.input :recipient_principal_scientist_state, :label => 'State' %>
    <%= f.input :recipient_principal_scientist_city, :label => 'City' %>
    <%= f.input :recipient_principal_scientist_zip, :label => 'Zip-Code' %>
    <%= f.input :recipient_principal_scientist_phone, :label => 'Phone' %>
    <%= f.input :recipient_principal_scientist_fax, :label => 'Fax' %>
    <%= f.input :recipient_principal_scientist_email, :label => 'E-Mail' %>
  <% end %>
  
  <%= f.inputs "Recipient Authorized Official", :id => "recipient_authorized_official" do %>
    <%= f.input :recipient_authorized_official_institute, :label => "Institution's Full Name" %>
    <%= f.input :recipient_authorized_official_person, :label => "Official's Full Name" %>
    <%= f.input :recipient_authorized_official_additional_address_line, :label => 'Additional Address Line' %>
    <%= f.input :recipient_authorized_official_street, :label => 'Street' %>
    <%= f.input :recipient_authorized_official_state, :label => 'State' %>
    <%= f.input :recipient_authorized_official_city, :label => 'City' %>
    <%= f.input :recipient_authorized_official_zip, :label => 'Zip-Code' %>
    <%= f.input :recipient_authorized_official_phone, :label => 'Phone' %>
    <%= f.input :recipient_authorized_official_fax, :label => 'Fax' %>
    <%= f.input :recipient_authorized_official_email, :label => 'E-Mail' %>
  <% end %>
  
  <%= f.inputs "Billing Address", :id => "billing_address" do %>
    <%= f.input :billing_address_institute, :label => "Institution's Full Name" %>
    <%= f.input :billing_address_additional_address_line, :label => 'Additional Address Line' %>
    <%= f.input :billing_address_street, :label => 'Street' %>
    <%= f.input :billing_address_state, :label => 'State' %>
    <%= f.input :billing_address_city, :label => 'City' %>
    <%= f.input :billing_address_country, :label => 'Country' %>
    <%= f.input :billing_address_reference, :label => 'Your Reference number or PO-Number (if applicable)' %>
  <% end %>
  
  <%= f.inputs "Tax Details", :id => "tax_details" do %>
    <%= f.input :tax_eu_member_state, :label => 'EU Member State?' %>
    <%= f.input :tax_eu_vat_id, :label => 'EU VAT ID (if applicable)', :hint => 'If your country of residence is within the EU, please provide us with your VAT ID. If you are tax-exempt and, do not have one, you do not need to supply us with one.' %>
  <% end %>
  
  <fieldset id="ordered_products" class="inputs">
    <legend><span>Order Details</span></legend>
    
    <% unless ordered_product_errors.empty? %>
      <div class="errorExplanation">  
        <h2>Errors were found when trying to process these products</h2>
        <ul>
          <% ordered_product_errors.uniq.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <table>
      <thead>
        <tr>
          <th>Gene</th>
          <th>Material</th>
          <th><span class="vertical">Genotyping</span></th>
          <th><span class="vertical">1 Extra Vial per Clone</span></th>
          <th><span class="vertical">Allele QC</span></th>
          <th><span class="vertical">Karyotyping</span></th>
          <th><span class="vertical">Replacement Vial(s)</span></th>
          <th class="price">Price (&euro;)</th>
        </tr>
      </thead>
      <tbody>
        <% @order.ordered_products.each do |ordered_product| %>
          <%= f.fields_for :ordered_products, ordered_product do |op| %>
            <tr class="ordered_product">
              <td><%= op.text_field :gene %></td>
              <td><%= op.collection_select(:ordered_product_type_id, OrderedProductType.all, :id, :product_type, { :include_blank => true }, { :class => 'ordered_product_type_id' }) %></td>
              <%
                check_box_options = { :disabled => true }
                if ordered_product.ordered_product_type_id && OrderedProductType.find(ordered_product.ordered_product_type_id).clone_count > 0
                  check_box_options.delete(:disabled)
                end
              %>
              <td><%= op.check_box :genotyping, { :class => 'genotyping' }.merge(check_box_options) %></td>
              <td><%= op.check_box :extra_vial_per_clone, { :class => 'extra_vial_per_clone' }.merge(check_box_options) %></td>
              <td><%= op.check_box :allele_qc, { :class => 'allele_qc' }.merge(check_box_options) %></td>
              <td><%= op.check_box :karyotyping, { :class => 'karyotyping' }.merge(check_box_options) %></td>
              <td><%= op.check_box :replacement_vials, { :class => 'replacement_vials' }.merge(check_box_options) %></td>
              <td><%= op.text_field :price, { :class => 'price', :readonly => true } %></td>
            </tr>
          <% end %>
        <% end %>
        <tr>
          <th colspan="7" style="text-align:right;">Subtotal</th>
          <td><%= f.text_field :subtotal_price, { :id => 'subtotal', :readonly => true } %></td>
        </tr>
        <tr>
          <th colspan="7" style="text-align:right;">Shipping</th>
          <td><%= f.text_field :shipping_price, { :id => 'shipping', :readonly => true } %></td>
        </tr>
        <tr>
          <%
            vat = @vat
            vat = 0.00 unless @order.tax_eu_member_state
          %>
          <th colspan="7" style="text-align:right;" id="vat_description"><%= vat %>&#37; VAT</th>
          <td><%= f.text_field :vat_price, { :id => 'vat', :readonly => true } %></td>
        </tr>
        <tr>
          <th colspan="7" style="text-align:right;">Total</th>
          <td><%= f.text_field :total_price, { :id => 'total', :readonly => true } %></td>
        </tr>
      </tbody>
    </table>
  </fieldset>
  
  <%= f.inputs "Aims of the Intended Experiments", :id => "aims_of_intended_experiments" do %>
    <%= f.input :usage_aims_of_experiments, :label => 'Aims of experiments' %>
    <%= f.input :usage_eu_projects, :as => :string, :label => 'Do you intend to use the material in EU-funded Project(s)? If yes, please insert project acronym(s)', :hint => 'This data is collected for statistical purposes only' %>
  <% end %>
  
  <%= f.buttons %>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_url %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Institute</th>
    <th>Principal Scientist</th>
    <th># Ordered Products</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.id %></td>
    <td><%= order.recipient_institute_name %></td>
    <td><%= order.recipient_principal_scientist_person %></td>
    <td><%= order.ordered_products.size %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_url(order) %></td>
    <td><%= link_to 'Destroy', order, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_url %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_url %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_order_url(@order) %> |
<%= link_to 'Back', orders_url %>